### ISSUE TITLE
Subsequent batch generations run with an error instead of applying lbw

### ISSUE THREAD

**Issue by jordanjay29** [nihedon/sd-webui-lora-block-weight#3]
```
*** Error running after_extra_networks_activate: [redacted]\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
    Traceback (most recent call last):
      File "[redacted]\modules\scripts.py", line 876, in after_extra_networks_activate
        script.after_extra_networks_activate(p, *script_args, **kwargs)
      File "[redacted]\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 600, in after_extra_networks_activate
        loradealer(self, kwargs["prompts"] ,self.lratios,self.elementals,kwargs["extra_network_data"])
      File "[redacted]\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 917, in loradealer
        lora_patches = lora_patches_list[lora_idx]
    IndexError: list index out of range

---
```

If the batch count is set above 1, this error appears just before inference begins on every image after the first, in place of where block weight would be applied. Block weight is applied normally on the first but seems to fail for the rest of a batch sequence.

**Comment by nihedon** [comment]
@jordanjay29 
Thank you for the report. I’ve fixed the issue. I’d appreciate it if you could check whether it’s working correctly.

**Comment by jordanjay29** [comment]
Seems to be working as intended now, my batch of count 2 just applied lbw to both generations. Worked as well with batch size 2. Fixed as far as I can tell!

**Comment by nihedon** [comment]
@jordanjay29 
Thank you for letting me know. I’m glad the issue has been resolved. If you encounter any other problems, please don’t hesitate to reach out.

Since this issue has been resolved, I will now close it.
